### ISSUE TITLE
Master test suite broken (undefined method `schema' for #<Class...)

### ISSUE THREAD

**Issue by sbleon** [apotonick/cells#416]
```
WorkerFileMarshallerTest#test_0001_anonymous:
NoMethodError: undefined method `schema' for #<Class:0x007fa97afea5f8>
    /Users/leon/code/gems/trailblazer-rails/lib/trailblazer/operation/worker.rb:82:in `file_marshaller_representer'
    /Users/leon/code/gems/trailblazer-rails/lib/trailblazer/operation/worker.rb:101:in `serializable'
    /Users/leon/code/gems/trailblazer-rails/lib/trailblazer/operation/worker.rb:18:in `run'
    /Users/leon/code/gems/trailblazer-rails/test/worker_test.rb:104:in `block in <class:WorkerFileMarshallerTest>'
```

I think the problem here *might* be that `schema` is an instance method on `Reform::Form`, not a class method.

**Comment by apotonick** [comment]
This is the wrong repository, buddy! :grimacing:

**Comment by sbleon** [comment]
Oh Jeez. That was silly of me! Sorry about that.
